### ISSUE TITLE
Setup command for contest [Python]

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#13]
Add a flag `-py` to `codemon init <contestName>` which would do initialisation described in #12 for python coders.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @ankingcodes

**Comment by ankushbhardwxj** [comment]
@subhangi2731 - We are not assigning issues so that everyone gets equal opportunity to work on an issue. If you can fix an issue, feel free to send a PR.
