### ISSUE TITLE
Setup command for contest [java]

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#14]
Add a flag `-java` to `codemon init <contestName>` which would do initialisation described in #12 for java coders.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @ankingcodes

**Comment by ankushbhardwxj** [comment]
@subhangi2731 - We are not assigning issues so that everyone gets equal opportunity to work on an issue. If you can fix an issue, feel free to send a PR.

**Comment by alphaX86** [comment]
@ankingcodes I have made some files to resolve this issue, could you review and check it please?

**Comment by alphaX86** [comment]
I'm reworking this again "without" introducing changes
