### ISSUE TITLE
User register

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#15]
Add a command `codemon reg` which would ask for Name, Codeforces username, password, Github username, Github password, Github competitive programming repository URL etc. which would be saved at a directory named `.codemon` by the filename `meta`. Also, add custom templates by the name of `template_py`, `template_cpp`, `template_java` inside the `.codemon` folder.

**Comment by lucifer0987** [comment]
@ankingcodes can you please explain this?
Whats ".codemon" here and what does "." stand for?
Thanks!

**Comment by ankushbhardwxj** [comment]
In UNIX/Linux, hidden files and directories are represented as `.` in front of them

**Comment by lucifer0987** [comment]
@ankingcodes Where should this .codemon directory be created at?
In the project folder?

**Comment by ankushbhardwxj** [comment]
> In the project folder?

@lucifer0987 - No, the are to be created at the root directory of Linux, denoted by `~/`.
