### ISSUE TITLE
Improve "codemon init -n"

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#16]
- [x] Add flags `-py`, `-cpp`, `-java` which would create a file with the extension matching to the flag and use the associate template `template_<type>` stored at `~/.codemon` (at root).
- [ ] Add flag `-t <template_name>` which would create file with specified template name. If template doesnt exist, show error.
- [ ] Add functionality to fetch testcases from codeforces for a single file by intelligently parsing its contest number and problem name from the file name .

**Comment by paramsiddharth** [comment]
Could you please elaborate the last point? Thank you!

**Comment by ankushbhardwxj** [comment]
@paramsiddharth - Currently if we create a file using `codemon init -n` we get a file with the given filename, inside of which we have an header such as:
```cpp
 /*
   author: @ankingcodes
   created: 2020-11-29 12:37:45.668803
*/
#include<bits/stdc++.h>
```
We want to get the username from `~/.codemon/meta` and use it here along with the time of creation of the file.

**Comment by ag-hcoder** [comment]
@ankingcodes Can this issue be resolved into separate smaller issues? I'm willing to work on the one you mentioned above

**Comment by ankushbhardwxj** [comment]
@ag-hcoder - Yeah, they may be resolved but as you'd notice, all of them are interdependent on each other, I'd advice you to work on each of them so that I can award you maximum points.

**Comment by ankushbhardwxj** [comment]
Note: If the template file is not present at root, we have to generate it automatically.

**Comment by ag-hcoder** [comment]
> @ag-hcoder - Yeah, they may be resolved but as you'd notice, all of them are interdependent on each other, I'd advice you to work on each of them so that I can award you maximum points.

Sure
