### ISSUE TITLE
Scrape codeforces and fetch input output

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#17]
Command : `codemon fetch` inside contest directory.
- Check if the current working directory is a contest directory ? If not, display error message to `cd` into a contest directory.
- Parse the contest number from the directory name, if contest number is not parsed, display error message to rename directory with the contest number i.e., if contest round is Codeforces Round 1234 then directory should be named `1234` or maybe `round1234`. Contest number should be present mandatorily.
- Alternately give user option to add contest name as `codemon fetch <contestName>` .
- After getting the contest number, go to Contest URL (https://codeforces.com/contest/1234/problems), scrape all inputs and outputs and store in respective question folder. For example, inputs and outputs of problem A should be stored in `A/a.in` and `A/a.out` respectively.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @ankingcodes

**Comment by ankushbhardwxj** [comment]
@subhangi2731 - We are not assigning issues so that everyone gets equal opportunity to work on an issue. If you can fix an issue, feel free to send a PR.

**Comment by Enigmage** [comment]
@ankingcodes I have made a PR for this issue, please review.
