### ISSUE TITLE
codemon test & push

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#19]
- [ ] Add a command `codemon test <problem_name>` to run diff between output of particular program and testcase generated output.
- [ ] Add `codemon push` to push to git repository using git username and password available at `~/.codemon/meta`.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @ankingcodes

**Comment by ankushbhardwxj** [comment]
@subhangi2731 - We are not assigning issues so that everyone gets equal opportunity to work on an issue. If you can fix an issue, feel free to send a PR.

**Comment by ag-hcoder** [comment]
> Add a command `codemon test <problem_name>` to run diff between output of particular program and testcase generated output.

@ankingcodes Could you please elaborate more on this point?

**Comment by ankushbhardwxj** [comment]
@ag-hcoder - When we compile a program using codemon, the executable is renamed and used as `prog`. But in #12 , we are going to introduce a new directory structure, wherein, we will be able to scrape outputs available at the codeforces website for a problem and then store it in an `.op` file within the problem directory. 
Using `codemon test` we want to run "diff" between the outputs of `prog` and the `.op` file and then show if any changes were present. Similar to using `git diff`. Watch [this](https://www.youtube.com/watch?v=JXTVOyQpSGM&t=3s) by Errichto, especially the testing part to understand what exactly we want to do here.

**Comment by ag-hcoder** [comment]
I get your point but many at times in cf there are many possible solutions to input, there is no unique answer, how we are going to tackle these?

**Comment by ankushbhardwxj** [comment]
That is not our lookout then, we just care about matching sample outputs to our outputs and show difference between them. If its given in question that it may have many possible solutions then its up to user if they want to use codemon test or not.

**Comment by ankushbhardwxj** [comment]
Currently, codemon listen performs diff operation, so this issue is closed for now.
