### ISSUE TITLE
add a help section for common queries in codemon

### ISSUE THREAD

**Issue by lucifer0987** [ankingcodes/codemon#22]
we can add "codemon help" command for helping users with some simple queries regarding the use of codemon on different operating systems.
I would also like to work on it once its approved.

**Comment by ankushbhardwxj** [comment]
@lucifer0987 - codemon currently displays help messages on simply typing `codemon`. But I like your suggestion too, instead of `codemon help` you can add a flag `codemon --help`

**Comment by lucifer0987** [comment]
Ok sure. 
Thanks!!

How should raise a PR?
Should i create a new branch or raise a PR to the main branch only?
And, i should also clean the build files, right?

**Comment by ankushbhardwxj** [comment]
Create a separate branch for each PR. 
> And, i should also clean the build files, right?

Yeah, add them to `.gitignore`

**Comment by lucifer0987** [comment]
@ankingcodes should I close this now?
