### ISSUE TITLE
codemon clean

### ISSUE THREAD

**Issue by lucifer0987** [ankingcodes/codemon#23]
Follow up to this issue #12 

It will be used to delete redundant files left after the contest as discussed in the issue above. We will have a lot of redundant files which will simply eat our storage.
codemon clean will clear up all the mess(prog, input.txt, testcase files) after a contest.

There is a catch to this. We can't randomly delete the mess. We can directly delete prog. But for input.txt, we must check whether it contains something, if its empty delete it else give an error message saying "Input file is not empty, do you want to delete ? (Y/N)` and user can decide what to do with it. For the testcase files, we have to "diff" them before deleting, i.e., if the testcase files had no changes in it then it can be deleted else if any kind of changes was done, they must stay.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @lucifer0987

**Comment by lucifer0987** [comment]
@subhangi2731 yes, you can work on this.
but, i guess, first i need to complete the issue #12 then, only you can work on cleaning the residual files.

**Comment by ankushbhardwxj** [comment]
Reiterating the tasks :
- Check all the files in a contest directory, diff them & see if it has any new content or just previous content. 
- Delete all files which have remained unchanged, except input file and output files.

**Comment by devsTudu** [comment]
Hello, can you assign this to me

**Comment by lucifer0987** [comment]
@ankingcodes Can you please explain this issue once more?

**Comment by ankushbhardwxj** [comment]
Done 72938ac11f63f7fbf8f5b59e811fd8cc7c87e861 !
