### ISSUE TITLE
Stop running output if compilation fails

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#25]
Currently, when compilation fails, the program proceeds to the next step by displaying the output by running the `prog` file which is unnecessary. Therefore if program compilation fails simply display the errors and dont proceed to display program output.

**Comment by Enigmage** [comment]
Hey, I'd like to work on this issue, can you assign this to me? 
Also, I had a question, in case of an error do you want codemon to display some error message of its own, for example:
 ``` codemon: Found an error. Stopping execution. ```
Something like this. 
Or, leave it as it is with just the original error message from the compiler ?

**Comment by ankushbhardwxj** [comment]
@Enigmage - It's a quick fix issue, currently are compiling C++ code and simply moving on to the next step of displaying output without verifying compilation passed or failed. Therefore, we just need to stop showing output if compilation failed and only show output if compilation passed. 
We don't need a specific error message from codemon, just the ones from g++ are enough.

**Comment by Enigmage** [comment]
Okay so I'll leave the original error output as it is. So I've fixed this, just have to check the output from `os.system` . There is an error if output is not zero, so based on that we can stop execution. Is it okay if I make a PR for this?

**Comment by ankushbhardwxj** [comment]
Yeah, you may proceed with a PR.

**Comment by Enigmage** [comment]
Hey @ankingcodes I made a new PR with the requested changes since there were a lot of merge conflicts in the previous one. You can check it out.
