### ISSUE TITLE
Fix indent of template

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#35]
![22](https://user-images.githubusercontent.com/40923324/100835747-1a8a2f80-3494-11eb-9070-a502e9328422.PNG)

A better fix for this would be to fetch template corresponding to file extension (cpp, java, py) from a directory `.codemon/templates/` (note the `.`, since its hidden) from root directory (`~/`).

**Comment by ankushbhardwxj** [comment]
@lucifer0987 - I think you can work on this. Let me know 👍🏻

**Comment by lucifer0987** [comment]
@ankingcodes yeah sure, I would love to.
I have to create templates for cpp, java and py. These should be stored in '.codemon/templates/' directory.
And, whenever a new file of this extension is created, it should fetch the corresponding template from this directory.

> `.codemon/templates/` (note the `.`, since its hidden) from root directory (`~/`).

I didn't understand this part.

You also talked about fixing the indent. whats that?

**Comment by ankushbhardwxj** [comment]
> I have to create templates for cpp, java and py. These should be stored in '.codemon/templates/' directory.
> And, whenever a new file of this extension is created, it should fetch the corresponding template from this directory.

Don't work on this yet. There's a PR already made for java.

> You also talked about fixing the indent. whats that?

Just go to CodemonMeta and fix the indent of CPP Template string there. (It should be aligned to the side, with spaces in specific places) as follows:

![23](https://user-images.githubusercontent.com/40923324/100849879-04d33500-34a9-11eb-988a-0adb6d18a8f4.PNG)

**Comment by lucifer0987** [comment]
@ankingcodes 
should I work on this issue or not?

**Comment by ankushbhardwxj** [comment]
I believe I have indicated what you have to do.

**Comment by lucifer0987** [comment]
@ankingcodes 
Don't get me wrong please. I am sorry for this. 


> > I have to create templates for cpp, java and py. These should be stored in '.codemon/templates/' directory.
> > And, whenever a new file of this extension is created, it should fetch the corresponding template from this directory.
> 
> Don't work on this yet. There's a PR already made for java.

You said "don't work on this".

> > You also talked about fixing the indent. what's that?
> 
> Just go to CodemonMeta and fix the indent of CPP Template string there. (It should be aligned to the side, with spaces in specific places) as follows:

and, then, you told me to do something.
I was really confused. So, I asked.

I am confused now as well. Really sorry.

**Comment by ankushbhardwxj** [comment]
> Just go to CodemonMeta and fix the indent of CPP Template string there. (It should be aligned to the side, with spaces in specific places) as follows:

Sorry for misunderstanding, you're supposed to do this part that I've quoted.
