### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by Enigmage** [ankingcodes/codemon#37]
To streamline the development process and prevent any future conflicts from happening, it might be a good idea to add clear and concise Contribution guidelines and Code of Conduct to the documentation of this repo, specially in light of the recent PR conflicts that happened. 

Some example  guidelines we can add for contributors:
- Make short and concise PRs that handle one issue at a time as they are considered good practise and are easy for the mentor to test and integrate  into the project. 
- Specific to this repo and nWoC, no issue opened by the Mentor will be assigned to anyone and that only self opened issues, if approved by the mentor, will be considered assigned since this is a competetive program.

etc etc.

We can also include Coding Style guidelines (indentation rules etc).
All this can prevent future conflicts and might help the project greatly.

@ankingcodes  If you're interested in this suggestion I can make PRs to help add the necessary documentation to the project.

**Comment by ankushbhardwxj** [comment]
Hey @Enigmage - Thanks for the suggestion, but we are not looking to make changes to the README. Regarding Coding Style guidelines, I'd be more interested if you'd setup some kind of automation CI tool like preetier, which would review every PR made to this repository for its code style and indentation. Do you have any ideas in this regard ?

**Comment by Enigmage** [comment]
There would be no need to change the README, just a new file **Contributing.md** will be added, link to which will be visible to anyone making a PR to this repo. About the CI system, yeah I can help setting up something like [pycodestyle](https://github.com/marketplace/actions/pycodestyle) through github actions that will check code style in all PRs according to PEP 8 standards. So should I close this issue and open a new one for setting up CI ?

**Comment by ankushbhardwxj** [comment]
Yeah you can close this and create a new issue for CI. However, please present some more options for style checking. I'm not sure if pycodestyle is reliable.

**Comment by Enigmage** [comment]
Yeah sure I'll definitely look into more options and keep you updated.
