### ISSUE TITLE
improve installation

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#4]
installation is quite buggy. Test if it works and improve if possible.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN hey what's up ? This is my first python project. Its an awesome tool for competitive programming. The installation was buggy, however, I made some improvements in it. Please try installing it and please let me know if its buggy ? Also, I'd be grateful if you could help me with some more improvements and also how to make this an actual python package on PYPI.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@ankingcodes thats really useful tool. Will test out and let you know. I'm not an expert on python so I have no idea about publishing to pypi. Sorry!

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN Cool ! Try to install it and let me know if something is wrong.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
You could try using codeforces API to get inputs of problems i guess So instead of making it manually entering in input.txt it would be nice if u can extract from cf and test it on the code see if the output matches.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Works like a charm for me :) Great job though!

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN  actually I did think about getting inputs from codeforces, but the API doesn't support such a feature. Since most students use codechef too, and also codechef doesn't have an API, i am thinking of making a web scraper which can scrape the current url on browser and get inputs from the fields. What do u think ?
Also , if you like it please give a ⭐️

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Web scrapper sounds great but im not really sure if those sites will allow a bot to scrape freely especially during contests(heavy load) but u can try to make it work. I would love that feature in this😇. Thank you for such a wonderful app.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN Hi ! I'm stuck on a project. I'd really appreciate it if you can give me some suggestions on it. Let me know when you're free.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Yeah where are you stuck, ill try my best to help you 😃

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN Okay, first I'll give u some background info. about the project. 
In C++ object oriented programming, we have classes and relations(inheritance) between classes. Also these classes have many different properties inside of them. This project is to help non-devs where the non dev draws diagrams and relations on a canvas and its converted to code automatically for them. However, a dev can also use an in browser code editor to write code which would simultaneously generate diagram. All of this should be done on React. 

As you can probably guess, there should be an application state, which should get updated by both the code editor and diagram editor when an user modifies something. So, I started implementing the project, the code to diagram part, where a guy suggested me to use a parser for parsing the code. When that parser is used, we get a class based output called a model file. This model file parses out all information regarding the classnames, relationships, properties etc, from the code which I easily used and converted code to diagram. 

The problem comes here, we want the diagram to update the model file too. I am unable to pass the modelfile to state and updating it is rather difficult. Someone suggested me to create a non react class similar to model file, rather than using state, which would get updated. Do you know  anything regarding this ? Can we actually create an external class in a js file and integrate it with react such that it gets updated onChange ?

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Ahhhhh I get what are you are trying to ask. This would be a better conversation to have in a instant messaging platform( like IRC) ping me when you are free. Join server Freenode and dm ( Rajagopalan) 👍🏻

**Comment by ankushbhardwxj** [comment]
I don't really use IRC. Are u available on Whatsapp or Telegram ?
