### ISSUE TITLE
Unit Tests for each command

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#45]
We need to add some tests for each command in `codemon`. This is just to make sure each command is doing the work it is supposed to. Test for each command should be written in a separate file, eg, for `codemon init` , create a file `codemonInitDirTest.py` , and so on. Also, create a single master script `build.py` or `runTests.py` which would run all the tests. 

These scripts would also be useful in #44 
Check example test available in the test directory

**Comment by InfiniteVerma** [comment]
I'll like to work on this.

**Comment by ankushbhardwxj** [comment]
@InfiniteVerma - Go ahead and send a PR. Note new features of codemon and multiple language support that has been added in recent PR #55

**Comment by ankushbhardwxj** [comment]
Fixed via 909cc1c
