### ISSUE TITLE
[SUGGESTION] Add 2D ANSI based logo for the tool

### ISSUE THREAD

**Issue by alphaX86** [ankingcodes/codemon#53]
### What is this about?
I've seen some script tools and witnessed that they use some kind of ANSI based lettered logos in it. For example, run neofetch script in Linux, it'll print a vibrant colored logo made of letters. Like that, we can try to implement.

Though, it's a suggestion, it's your call to think on this and review it. So, yep. Awaiting for your reply

**Comment by ankushbhardwxj** [comment]
@alphaX86 - Do you have any design ready for it ? And when would this graphic be shown ? During `codemon --help` ?

**Comment by alphaX86** [comment]
Yes exactly @ankingcodes. During `codemon` and `codemon -- help`

**Comment by alphaX86** [comment]
If you allow this one as valid issue, I'll make a design and send it in gitter. We can validate and the design will be made accordingly

**Comment by ankushbhardwxj** [comment]
@alphaX86 - I'm not quite sure about adding this as I prefer keeping CLIs simple and hassle free. 
Tagging @paramsiddharth @lucifer0987 @Enigmage for their opinion on this issue.

**Comment by paramsiddharth** [comment]
@ankingcodes I personally think an ANSI-based logo will be a good addition to the application. It would definitely make it more appealing, and since it will be ANSI-based, it won't add much to the size. Besides, I have seen @alphaX86 work with ANSI-based logos before. I'm sure he will have a good design ready for Codemon.

**Comment by ankushbhardwxj** [comment]
Cool ! @alphaX86 : you may proceed with a design for this, try to keep it minimal. We might use that on our README as well.

**Comment by alphaX86** [comment]
Sure! Will do that

**Comment by alphaX86** [comment]
I'll send the designs in gitter. You can choose what type you want. Is it okay @ankingcodes ?

**Comment by alphaX86** [comment]
@ankingcodes the PR is created. If you're uncomfortable with the present one I have given and need changes, refer link in the PR I mentioned (#62 )

**Comment by alphaX86** [comment]
PR merged. So closing this issue
