### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by Tejas1510** [ankingcodes/codemon#56]
The project is currently missing the Code of Conduct file which is important for open source project
So can I go for it @ankingcodes

**Comment by ankushbhardwxj** [comment]
@Tejas1510 - As this is not a big project we are not looking to add a Code of Conduct file specifically for the project. Students have already read code of conduct from NWOC github repo.

**Comment by Tejas1510** [comment]
Sure @ankingcodes
