### ISSUE TITLE
Improve README.md file

### ISSUE THREAD

**Issue by KerinPithawala** [ankingcodes/codemon#57]
I think it is important to have contributing guidelines so that an open-source contributor know how to contribute properly.
Can I work on this?

**Comment by ankushbhardwxj** [comment]
@Kerveyfelix - Installation procedures are laid out on our README, and all students are supposed to read contribution guidelines from the NWoC github repo itself, so we are not adding contributing guidelines to the project. Basic instructions are laid out in README. 

You may however make changes to the README by making it more attractive. Maybe a list of contributors, maintainers (*only myself right now) or some badges, also improve the Codemon Header using some new font or JPG. 

But make sure to keep it minimal and simple. We don't want to clutter our readme with a lot of colourful stickers or emojis.

**Comment by KerinPithawala** [comment]
Noted. I can work on README.md updation without overcrowding it with stick, gif and other things.

**Comment by ankushbhardwxj** [comment]
@Kerveyfelix - If you're working on the README, note that will the merge of #55 , we have lots of new features for codemon such as support for languages such as java & Python and also automated fetching of inputs or outputs from the codeforces website. So make sure to include those points on the README. Thanks !

**Comment by KerinPithawala** [comment]
Noted.

**Comment by ankushbhardwxj** [comment]
Another thing, please get rid of the current GIF and update it with a new GIF, which displays the current working of Codemon (let me know if you encounter problems using the commands).

**Comment by KerinPithawala** [comment]
Noted.

**Comment by KerinPithawala** [comment]
Pip is not working on my PC.

**Comment by ankushbhardwxj** [comment]
@Kerveyfelix - What's the error exactly? Did you install pip3 properly ? Or you're unable to install codemon using pip3 ?

**Comment by sourav-suku** [comment]
@ankingcodes  Can I work on this as it is a good first issue for beginners like me.
I wanted to know, is @Kerveyfelix still working on this issue??

**Comment by ankushbhardwxj** [comment]
@sourav-suku - you can go ahead and make a PR for it. If @Kerveyfelix also sends in a PR, I'll merge the better one.

**Comment by ankushbhardwxj** [comment]
Done via 5eeec42143cfb69f8aa32c324258a5855425e34a
