### ISSUE TITLE
In Linux we have two output but we need only one 

### ISSUE THREAD

**Issue by TusharDasMe** [ankingcodes/codemon#60]
![is](https://user-images.githubusercontent.com/49882188/101352700-8ddad980-38b8-11eb-8c39-a4da5b293bd3.jpg)
in linux the file save two times thats why we have two output .

**Comment by ankushbhardwxj** [comment]
@TusharDasMe - confirming this issue. I'm getting the compilation and output step occurring twice when a file is saved on UNIX based systems. Reproduced on WSL terminal using Vim & VsCode.

**Comment by ankushbhardwxj** [comment]
Solution involves usage of [Event Queue](https://pythonhosted.org/watchdog/api.html#watchdog.observers.api.EventQueue), that skips adding the same event (FileSystemEvent) multiple times consecutively.

**Comment by paramsiddharth** [comment]
I can confirm the same happens in Windows (CMD, PowerShell, WSL) and MSYS2 as well.

**Comment by ag-hcoder** [comment]
@ankingcodes @paramsiddharth Can you elaborate more on the usage of Event Queue? I am working on this

**Comment by ankushbhardwxj** [comment]
This issue has been fixed in the new release 3101dfb
