### ISSUE TITLE
Improving the efficiency of template in codemonMeta.py

### ISSUE THREAD

**Issue by sourav-suku** [ankingcodes/codemon#61]
More functionalities and macro definitions could be included so as make the coding part even easier

**Comment by ankushbhardwxj** [comment]
@sourav-suku - can you post a sample template here ?

**Comment by sourav-suku** [comment]
#include <bits/stdc++.h> 
using namespace std;
const long long int M = (int)1e9+7;
#define rep(i,a,b) for(int i=a;i<b;++i)
#define repb(i,a,b) for(int i=a;i>=b;--i)
#define ll long long
#define sz(a) (ll)a.size()
#define ssortA(arr)   stable_sort(arr.begin(),arr.end())
#define ssortB(arr)   stable_sort(arr.begin(),arr.end(),greater<int >());
#define pii pair<int,int>
#define ff first
#define ss second
#define pb   push_back
#define pf push_front
#define mp make_pair
#define lb lower_bound
#define ub upper_bound
#define endl "\n" 
#define PI acos(-1.0)
#define GCD(a,b) __gcd(a,b)
#define popcount(x) __builtin_popcountll(x)
#define IOS ios_base::sync_with_stdio(false);cin.tie(NULL);cout.tie(NULL)
#define fix(f,n) fixed<<setprecision(n)<<f<<endl
#define checkin(ds, a) (ds.find(a)!=ds.end()?1:0)
#define mem(arr)  memset(arr,false,sizeof(arr))
#define eq(f1,f2) ((fabs(f1-f2)<=(double)1e-15))

int main(){
    IOS;
    int t;
    cin>>t;
    while(t--){

    }
    return 0;
}

**Comment by sourav-suku** [comment]
Sorry for the delay in my response
