### ISSUE TITLE
Improvements for "codemon fetch"

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#66]
- When inputs and outputs are written in the `.in` and `.op` files, there's an additional newline at the top of each file, which can cause problems in diffing between outputs during `codemon listen`, therefore, we need to avoid adding that newline either during write or be remove post write.
- Improve all verbose messages and use consistent coloring, currently, some of them are green and some are yellow, in a very inconsistent way. Maybe stick to white or some other bright colour which will be good for a basic terminal.
- Maybe get rid of `codemon fetch <contestName>` ? This needs discussion. Currently there are 3 ways to leverage the fetching functionality: `codemon fetch` inside contest directory, `codemon init -f <contestdir>`, `codemon fetch <contestName>`. The last one creates a directory with given contest name and contains only inputs and outputs and no code files. I believe we have already served that purpose with `codemon init -f <contestDir>`, therefore we can get rid of this command.

**Comment by Enigmage** [comment]
@ankingcodes I agree, the command does seem redundant to the current functionality. I think we should remove it.  There are also a few inconsistencies in `CodemonFetch` module that I want to fix. I'll make a new PR for all this.

As for the second one I think it can be a separate issue, make coloring of all verbose messages consistent and also add better verbose messages for a better user experience. What do you think?

**Comment by ankushbhardwxj** [comment]
@Enigmage - Yeah, I agree with this. But I'm not a big fan of long messages. Make them verbose wherever required, but try to keep them concise and to the point.
