### ISSUE TITLE
Add a sensible default template (python)

### ISSUE THREAD

**Issue by Enigmage** [ankingcodes/codemon#69]
Currently we don't have a proper default template for python. This is the template that gets added to source files during init if the user does not have a custom template in `~/.codemon/` folder. 

The goal is to have a sensible default template that is capable of taking care of the basic needs of the user during a competitive programming contest without having too much boilerplate.

The template can be added in the `template` string under `default_py` method of the `Templates` class in the `CodemonMeta` module.

**Comment by ankushbhardwxj** [comment]
@Enigmage - Go ahead and send in a PR

**Comment by lucifer0987** [comment]
@ankingcodes what improvements you want in this template?

**Comment by Siddhant-K-code** [comment]
***Can We Use this?***
```
from os import path
from io import BytesIO, IOBase
import sys
from heapq import heappush,heappop
from functools import cmp_to_key as ctk
from collections import deque,Counter,defaultdict as dd 
from bisect import bisect,bisect_left,bisect_right,insort,insort_left,insort_right
from itertools import permutations
from datetime import datetime
from math import ceil,sqrt,log,gcd
def ii():return int(input())
def si():return input().rstrip()
def mi():return map(int,input().split())
def li():return list(mi())
# mod=1000000007
mod=998244353
inf = float("inf")
file = 1
 
# write fastio for getting fastio template.
    
 
def solve():
 
 
    # Your Solution


        
if __name__ =="__main__":
 
    if(file):
 
        if path.exists('input.txt'):
            sys.stdin=open('input.txt', 'r')
            sys.stdout=open('output.txt','w')
        else:
            input=sys.stdin.readline
    solve()
```

**Comment by ankushbhardwxj** [comment]
@Siddhant-K-code - Looks good. Send in a PR !

**Comment by Siddhant-K-code** [comment]
@ankingcodes Please Review #74
