### ISSUE TITLE
create custom inputs for problem

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#7]
This would be an alternative to the webscraping problem. 
There's a video on YouTube where Errichto generates test cases and inputs for his coding problems. This would be a great addition in a place where the webscraper fails.

**Comment by ankingcodes** [comment]
@Errichto check out this tool I made after watching your competitive programming setup video on YouTube. Let me know if you enjoy using this 👍 🚀 🎉
