### ISSUE TITLE
Adding custom templates 

### ISSUE THREAD

**Issue by cs-mshah** [ankingcodes/codemon#71]
It would be great if we could add our custom templates that we generally use, as most of the programmers use their own templates, which vary. So if a template path is specified, then codemon should load that, else the default template is used.

**Comment by cs-mshah** [comment]
Please assign me this issue

**Comment by ankushbhardwxj** [comment]
@cs-mshah - This case is already handled, codemon searches for template file at a hidden directory (`~/.codemon`) at root of linux directory system. If a template is not found, only then the default templates are used. You may close the issue if this answers your query.
