### ISSUE TITLE
Contributors Image In Readme

### ISSUE THREAD

**Issue by Vishal-raj-1** [ankingcodes/codemon#73]
I think it is a great feature to add contributors image in README file. It really motivate to contributors. It is dynamically order the contributors. 

![contrimga](https://user-images.githubusercontent.com/59874304/102012505-dd198200-3d70-11eb-8e1e-379f47ccd7e2.JPG)

If you want to this feature on README so I want to do this issue @ankingcodes  Sir !! 😄

**Comment by ankushbhardwxj** [comment]
People can already see contributors on the right side when they open our repository so I think it doesn't make sense to add them to the README.

**Comment by Vishal-raj-1** [comment]
> People can already see contributors on the right side when they open our repository so I think it doesn't make sense to add them to the README.

No !! They can see few of them only
