### ISSUE TITLE
[FEAT] C++ template can be updated 

### ISSUE THREAD

**Issue by alphaX86** [ankingcodes/codemon#75]
Hello maintainer, I just came across this CP template and it's really awesome!

[CP Template Gist](https://gist.github.com/alphaX86/ad925deb146b66f7ab3149318adb4fb0)

What's your opinion??? And don't tag me this time for comment!!! Just say your review bro, and don't tag me!

**Comment by alphaX86** [comment]
Seriously, don't tag me :(

**Comment by ankushbhardwxj** [comment]
We are not looking to make changes to the default C++ template, we have provided functionality for user to use their own templates in their programs. Therefore, closing this issue now.
