### ISSUE TITLE
Codemon is not testiing my solution [Mac]

### ISSUE THREAD

**Issue by chilligon** [ankingcodes/codemon#82]
Hi! This is Chilliagon. I really like this tool . I just came to know about it today
I tried to try it in today's contest , the parsing is perfect but even though i am saving it and running the command listen . It doesn't compile my program . I am working on mac. Can you please help

**Comment by ankushbhardwxj** [comment]
Hi @chilligon - can you provide some screenshot or maybe a log of the error message ?

**Comment by chilligon** [comment]
Hi @ankingcodes - there is no error message that is coming  - it just pauses and nothing happens. Thanks for quick reply though!

**Comment by ankushbhardwxj** [comment]
@chilligon - fixed your issue ! Check out the new release.

**Comment by chilligon** [comment]
Hi @ankingcodes tried it again today! still the same issue
![Screenshot 2021-03-02 at 6 54 45 PM](https://user-images.githubusercontent.com/78139281/109654919-c3762280-7b88-11eb-81df-ad812b8d8ddd.png)
Still even though I have changed the file its not judging. Please help!

**Comment by ankushbhardwxj** [comment]
@chilligon That's strange ! Did you update the project to the latest commit ? If not, I'd suggest you to remove codemon and do a fresh install. You can type `whereis codemon` and get rid of the binary. After that clone this repository, and follow the following steps:
```bash
# fresh install
git clone https://github.com/ankingcodes/codemon
cd codemon/
pip3 install .

# create a new contest directory or file
codemon init -n <singleFileName>
# OR 
codemon init <directoryName>
# to start listening
codemon listen 
# open any of the code files and write some code
# MUST hit save inside the code file for codemon listen to capture the file for compilation 
```
This is a program and output which works on my terminal. 
```cpp
/*
  author: @ankingcodes
  created: 2021-03-02 20:15:27.329373
*/
        
#include<bits/stdc++.h>
using namespace std;
#define ll long long
#define MOD 1000000007

int main(){
  ios_base::sync_with_stdio(false);
  cin.tie(NULL);
  cout << 2 << endl;  
  return 0;
}

```
Output: 
```
Getting files in directory
Currently listening for file changes
Compiling A.cpp...
No input found.
Output:
2
```
